FROM raychee/python3-teradata

WORKDIR /jupyter

RUN yum install -y gcc gcc-c++ git make

RUN conda create -y -n py3 python=3 ipykernel anaconda teradata && \
    source activate py3 && \
    ipython kernel install --user && \
    conda clean -y --all && \
    conda create -y -n py2 python=2 ipykernel anaconda teradata && \
    source activate py2 && \
    ipython kernel install --user && \
    conda clean -y --all

# Install xgboost
RUN cd /opt && \
    git clone --recursive https://github.com/dmlc/xgboost && \
    cd xgboost && \
    git submodule init && \
    git submodule update && \
    ./build.sh && \
    cd python-package && \
    source activate py3 && python setup.py install && \
    source activate py2 && python setup.py install && \
    cd / && \
    rm -rf /opt/xgboost

CMD source activate py3 && \
    jupyter notebook --ip='*' --port=8888 --NotebookApp.token='' --allow-root --no-browser
