FROM centos:7

RUN yum install -y bzip2 && \
    echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh
ENV PATH /opt/conda/bin:$PATH

# Install Python (miniconda)
RUN curl -O https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh && \
    bash Miniconda2-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm -f Miniconda2-latest-Linux-x86_64.sh && \
    conda update -y --all && \
    conda clean -y --all
